[2023-02-04 07:34:14,484] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.python_sensor manual__2023-02-04T07:21:44.493696+00:00 [queued]>
[2023-02-04 07:34:14,495] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.python_sensor manual__2023-02-04T07:21:44.493696+00:00 [queued]>
[2023-02-04 07:34:14,495] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 07:34:14,496] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-04 07:34:14,496] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 07:34:14,511] {taskinstance.py:1397} INFO - Executing <Task(PythonSensor): python_sensor> on 2023-02-04 07:21:44.493696+00:00
[2023-02-04 07:34:14,516] {standard_task_runner.py:52} INFO - Started process 6063 to run task
[2023-02-04 07:34:14,518] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'python_sensor', 'manual__2023-02-04T07:21:44.493696+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag_test.py', '--cfg-path', '/tmp/tmpv3f5a9g3', '--error-file', '/tmp/tmp0o7n8put']
[2023-02-04 07:34:14,518] {standard_task_runner.py:80} INFO - Job 122: Subtask python_sensor
[2023-02-04 07:34:14,583] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.python_sensor manual__2023-02-04T07:21:44.493696+00:00 [running]> on host 39df186e1726
[2023-02-04 07:34:14,649] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=python_sensor
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T07:21:44.493696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T07:21:44.493696+00:00
[2023-02-04 07:34:14,658] {python.py:66} INFO - Poking callable: <function check_rates_cnt_change at 0x7f1e0366a680>
[2023-02-04 07:34:14,666] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-02-04 07:34:14,691] {logging_mixin.py:115} INFO - 0 17
[2023-02-04 07:34:14,697] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/python.py", line 67, in poke
    return_value = self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yandex_dag_test.py", line 134, in check_rates_cnt_change
    if Variable.get("rates_rows_cnt") > temp_rates_cnt_rows:
TypeError: '>' not supported between instances of 'str' and 'int'
[2023-02-04 07:34:14,708] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=yandex-rates-test, task_id=python_sensor, execution_date=20230204T072144, start_date=20230204T073414, end_date=20230204T073414
[2023-02-04 07:34:14,718] {standard_task_runner.py:97} ERROR - Failed to execute job 122 for task python_sensor ('>' not supported between instances of 'str' and 'int'; 6063)
[2023-02-04 07:34:14,730] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-04 07:34:14,752] {taskinstance.py:1752} ERROR - Error when executing on_failure_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1750, in _run_finished_callback
    task.on_failure_callback(context)
  File "/opt/airflow/dags/yandex_dag_test.py", line 140, in _failure_callback
    if isinstance(context['exception'], AirflowSensorTimeout):
NameError: name 'AirflowSensorTimeout' is not defined
[2023-02-04 07:34:14,782] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
