[2022-11-05 16:14:07,053] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.import_rates manual__2022-11-05T16:13:52.395507+00:00 [queued]>
[2022-11-05 16:14:07,129] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.import_rates manual__2022-11-05T16:13:52.395507+00:00 [queued]>
[2022-11-05 16:14:07,134] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 16:14:07,136] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-11-05 16:14:07,138] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-11-05 16:14:07,439] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): import_rates> on 2022-11-05 16:13:52.395507+00:00
[2022-11-05 16:14:07,456] {standard_task_runner.py:52} INFO - Started process 5180 to run task
[2022-11-05 16:14:07,490] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'import_rates', 'manual__2022-11-05T16:13:52.395507+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag_test.py', '--cfg-path', '/tmp/tmpr4ffi7a0', '--error-file', '/tmp/tmpwe5q3hx1']
[2022-11-05 16:14:07,511] {standard_task_runner.py:80} INFO - Job 27: Subtask import_rates
[2022-11-05 16:14:07,919] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.import_rates manual__2022-11-05T16:13:52.395507+00:00 [running]> on host ec0dc6e942fe
[2022-11-05 16:14:08,182] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=import_rates
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T16:13:52.395507+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-05T16:13:52.395507+00:00
[2022-11-05 16:14:08,190] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yandex_dag_test.py", line 77, in import_codes
    url = dag_variables.get('url_base') + hist_date
NameError: name 'dag_variables' is not defined
[2022-11-05 16:14:08,218] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=yandex-rates-test, task_id=import_rates, execution_date=20221105T161352, start_date=20221105T161407, end_date=20221105T161408
[2022-11-05 16:14:08,274] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task import_rates (name 'dag_variables' is not defined; 5180)
[2022-11-05 16:14:08,343] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-11-05 16:14:08,560] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
