[2023-02-04 06:38:31,621] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data manual__2023-02-04T06:38:28.590178+00:00 [queued]>
[2023-02-04 06:38:31,628] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data manual__2023-02-04T06:38:28.590178+00:00 [queued]>
[2023-02-04 06:38:31,628] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 06:38:31,628] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-04 06:38:31,629] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 06:38:31,640] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2023-02-04 06:38:28.590178+00:00
[2023-02-04 06:38:31,644] {standard_task_runner.py:52} INFO - Started process 3221 to run task
[2023-02-04 06:38:31,646] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'insert_data', 'manual__2023-02-04T06:38:28.590178+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag_test.py', '--cfg-path', '/tmp/tmppbln0ip0', '--error-file', '/tmp/tmp32wsb4_2']
[2023-02-04 06:38:31,647] {standard_task_runner.py:80} INFO - Job 51: Subtask insert_data
[2023-02-04 06:38:31,710] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.insert_data manual__2023-02-04T06:38:28.590178+00:00 [running]> on host 39df186e1726
[2023-02-04 06:38:31,780] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T06:38:28.590178+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T06:38:28.590178+00:00
[2023-02-04 06:38:31,790] {logging_mixin.py:115} INFO - rate_date:  2023-02-04
[2023-02-04 06:38:31,791] {logging_mixin.py:115} INFO - value_:  23510.60869599999932
[2023-02-04 06:38:31,800] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-02-04 06:38:31,817] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yandex_dag_test.py", line 73, in insert_data
    cursor.commit(f"SELECT count(*) FROM {dag_variables.get('table_name')}")
AttributeError: 'psycopg2.extensions.cursor' object has no attribute 'commit'
[2023-02-04 06:38:31,826] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=yandex-rates-test, task_id=insert_data, execution_date=20230204T063828, start_date=20230204T063831, end_date=20230204T063831
[2023-02-04 06:38:31,837] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task insert_data ('psycopg2.extensions.cursor' object has no attribute 'commit'; 3221)
[2023-02-04 06:38:31,859] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-04 06:38:31,896] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
